# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2021-09-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_collada.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColladaScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=django_collada.models.scene_filename)),
                ('filesystem_path', models.TextField(blank=True, default=b'')),
                ('dae_file', models.CharField(blank=True, max_length=256, null=True)),
                ('file_type', models.CharField(blank=True, choices=[(b'dae', b'Collada file'), (b'zip', b'Collada ZIP archive (.dae + related assets)')], default=b'zip', max_length=16)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quick_collada', models.TextField(blank=True, default=b'')),
            ],
            options={
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FooBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(default=0.0)),
                ('y_coord', models.FloatField(default=0.0)),
                ('z_coord', models.FloatField(default=0.0)),
                ('color', models.CharField(default=b'ABCDEF', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SceneToDataSourceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=32)),
                ('foobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_collada.FooBar')),
            ],
        ),
        migrations.CreateModel(
            name='FooBarScene',
            fields=[
                ('colladascene_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_collada.ColladaScene')),
                ('update_interval', models.IntegerField(default=10000)),
                ('data_source_mappings', models.ManyToManyField(blank=True, to='django_collada.SceneToDataSourceMapping')),
            ],
            bases=('django_collada.colladascene',),
        ),
    ]
